"""Loss Explanation Engine — Decision Intelligence Phase 3, Step 8.

For every losing round trip, answers "was this a bad decision, or bad luck?"
by comparing entry confidence (ensemble_score at BUY time) against this
symbol set's own average, rather than a fixed threshold — the model's real
confidence range is narrow (roughly 0.53-0.64 in practice) and doesn't
support a hardcoded absolute cutoff. Pairs that with the factual exit-reason
narrative already generated by database.trade_journal.auto_lesson().
"""
from __future__ import annotations

from loguru import logger

from bot.core.error_logger import safe_render, timed
from bot.eval.loader import load_completed_trades
from database.trade_journal import auto_lesson
from dashboard.data import DB_PATH
from dashboard.design_system import (
    BORDER, LOSS, NEURAL, TEXT1, TEXT2, TEXT3,
    FONT_VALUE, WEIGHT_BOLD,
    TH, _section, _empty_state, _card, _wrap,
)
from dashboard.registry import ComponentSpec, RefreshGroup, register

_logger = logger

_MIN_FOR_BASELINE = 5     # need this many completed trades before an average confidence is meaningful
_CONFIDENCE_MARGIN = 0.02  # +/- this many points from the average counts as "meaningfully different"

_EXIT_REASON_MAP = {
    "SELL_TAKE_PROFIT":   "take-profit",
    "SELL_TRAILING_STOP": "trailing-stop",
    "SELL_TIME_EXIT":     "time-exit",
    "SELL_STOP":          "stop-loss",
    "SELL_GAP_DOWN":      "gap-down",
    "SELL":               "signal",
}

_EXIT_LABEL = {
    "SELL_TAKE_PROFIT":   "Take Profit",
    "SELL_TRAILING_STOP": "Trailing Stop",
    "SELL_TIME_EXIT":     "Time Exit",
    "SELL_STOP":          "Stop Loss",
    "SELL_GAP_DOWN":      "Gap Down",
    "SELL":               "Signal Sell",
}


def _confidence_tag(confidence: float, avg_confidence: float) -> tuple[str, str]:
    """(label, color) placing this trade's entry confidence relative to the
    average across all completed trades — not an absolute threshold, since
    the real confidence range is too narrow for a fixed cutoff to be meaningful."""
    if confidence <= avg_confidence - _CONFIDENCE_MARGIN:
        return "Bad decision — below-average confidence", LOSS
    if confidence >= avg_confidence + _CONFIDENCE_MARGIN:
        return "Bad luck — above-average confidence", NEURAL
    return "Near-average confidence — inconclusive", TEXT3


@timed(_logger)
@safe_render("Loss Explanation")
def render_loss_explanation() -> str:
    df = load_completed_trades(db_path=DB_PATH)
    if df.empty:
        return (
            f'<div class="nt nt-wrap">'
            f'{_section("🔍", "Loss Explanation", "")}'
            f'{_card(_empty_state("🔍", "No closed trades yet", "This builds as losing trades close."))}'
            f'</div>'
        )

    losses = df[df["pnl_pct"] < 0].sort_values("sell_ts", ascending=False)
    if losses.empty:
        return (
            f'<div class="nt nt-wrap">'
            f'{_section("🔍", "Loss Explanation", f"0 of {len(df)} completed trades")}'
            f'{_card(_empty_state("🔍", "No losses yet", "Nothing to explain — every closed trade so far has been a win or scratch."))}'
            f'</div>'
        )

    has_baseline = len(df) >= _MIN_FOR_BASELINE
    avg_confidence = float(df["ensemble_score"].mean()) if has_baseline else 0.0

    rows_html = ""
    n = len(losses)
    for i, (_, r) in enumerate(losses.iterrows()):
        border = f"border-bottom:1px solid {BORDER};" if i < n - 1 else ""
        symbol      = r["symbol"]
        confidence  = float(r["ensemble_score"])
        raw_reason  = r.get("exit_reason") or ""
        mapped      = _EXIT_REASON_MAP.get(raw_reason, raw_reason)
        label       = _EXIT_LABEL.get(raw_reason, raw_reason.replace("SELL_", "").replace("_", " ").title() or "—")
        lesson      = auto_lesson(mapped, float(r["pnl_pct"]), int(r["holding_days"]))
        date_s      = str(r["sell_ts"])[:10] if r["sell_ts"] is not None else "—"

        if has_baseline:
            tag, tag_color = _confidence_tag(confidence, avg_confidence)
        else:
            tag, tag_color = f"Need {_MIN_FOR_BASELINE}+ closed trades for a baseline", TEXT3

        # Single style attribute per cell — a second `style=` attribute on the
        # same tag is silently dropped by the browser (duplicate HTML attrs
        # keep only the first), so any override must live in this one string.
        rows_html += (
            f"<tr>"
            f"<td style='font-size:{FONT_VALUE};color:{TEXT1};font-weight:{WEIGHT_BOLD};padding:8px 14px;{border}white-space:nowrap;'>{symbol}</td>"
            f"<td style='font-size:{FONT_VALUE};color:{TEXT2};padding:8px 14px;{border}white-space:nowrap;'>{date_s}</td>"
            f"<td style='font-size:{FONT_VALUE};color:{LOSS};text-align:right;padding:8px 14px;{border}font-family:Courier New,monospace;white-space:nowrap;'>{r['pnl_pct']:+.1%}</td>"
            f"<td style='font-size:{FONT_VALUE};color:{TEXT2};padding:8px 14px;{border}white-space:nowrap;'>{label}</td>"
            f"<td style='font-size:{FONT_VALUE};color:{TEXT2};text-align:right;padding:8px 14px;{border}font-family:Courier New,monospace;white-space:nowrap;'>{confidence:.0%}</td>"
            f"<td style='font-size:{FONT_VALUE};color:{tag_color};padding:8px 14px;{border}"
            f"white-space:normal;overflow:visible;text-overflow:clip;max-width:none;min-width:180px;'>{tag}</td>"
            f"<td style='font-size:{FONT_VALUE};color:{TEXT3};font-style:italic;padding:8px 14px;{border}"
            f"white-space:normal;overflow:visible;text-overflow:clip;max-width:none;min-width:220px;'>{lesson}</td>"
            f"</tr>"
        )

    table = (
        f"<table style='width:100%;border-collapse:collapse;'>"
        f"<thead><tr>"
        f"<th {TH} style='text-align:left;'>Symbol</th>"
        f"<th {TH} style='text-align:left;'>Closed</th>"
        f"<th {TH} style='text-align:right;'>Return</th>"
        f"<th {TH} style='text-align:left;'>Exit</th>"
        f"<th {TH} style='text-align:right;'>Confidence</th>"
        f"<th {TH} style='text-align:left;'>Verdict</th>"
        f"<th {TH} style='text-align:left;'>Lesson</th>"
        f"</tr></thead><tbody>{rows_html}</tbody></table>"
    )
    subtitle = f"{n} of {len(df)} completed trades" + (
        "" if has_baseline else f" — need {_MIN_FOR_BASELINE}+ for a confidence baseline"
    )
    return (
        f'<div class="nt nt-wrap">'
        f'{_section("🔍", "Loss Explanation", subtitle)}'
        f'{_wrap(table)}'
        f'</div>'
    )


register(ComponentSpec("loss_explanation_out", RefreshGroup.SLOW, render_loss_explanation, priority=56))
