"""Core Phase 0 ledger service: append_ledger_row, chain verification,
deployment manifest lifecycle, and decision lifecycle state (derived, v1.2).

Per phase0_implementation_spec.md Section 3, there is deliberately no
generic update/delete exposed anywhere in this module for Group A/B tables
-- append_ledger_row is insert-only. As of v1.2, decision_events has zero
mutable-column exceptions: lifecycle state (OPEN/CLOSED) is derived by the
decision_state SQL view based purely on decision_outcome_events row
existence, so there is no "mark closed" step to call at all -- appending
the outcome event is the whole transition. (An earlier revision had
mark_decision_closed/mark_decision_analyzed updating a stored outcome_state
column; that was a subtle immutability violation, since the same row could
return different content depending on when it was read even though its
hash never changed. Removed -- see phase0_data_model.md v1.2 changelog.)
"""
from __future__ import annotations

import json
import sqlite3
from typing import Any

from ledger.hashing import GENESIS_HASH, canonical_json, compute_record_hash

# ── Group A table metadata: which payload fields are JSON-typed / boolean,
# needed to serialize for storage and to reconstruct the exact canonical
# payload dict during verification (the hash was computed on native
# dicts/bools, before storage-serialization). ─────────────────────────────

_LEDGER_TABLES: dict[str, dict[str, Any]] = {
    "candidate_evaluation_events": {
        "id_field": "candidate_event_id",
        "json_fields": {"screening_results"},
        "bool_fields": {"data_available", "required_models_available",
                         "evaluation_requested", "evaluation_completed"},
    },
    "decision_events": {
        "id_field": "decision_id",
        "json_fields": {"portfolio_snapshot", "market_context", "model_outputs",
                         "risk_checks", "intent", "data_completeness"},
        "bool_fields": set(),
    },
    "decision_outcome_events": {
        "id_field": "outcome_id",
        "json_fields": {"cost_breakdown"},
        "bool_fields": set(),
    },
    "risk_evaluation_events": {
        "id_field": "event_id",
        "json_fields": set(),
        "bool_fields": set(),
    },
    "approval_events": {
        "id_field": "approval_id",
        "json_fields": {"reason_checklist"},
        "bool_fields": set(),
    },
    "deployment_manifest_events": {
        "id_field": "event_id",  # v1.3: e.g. MFE-20260728-001, auto-generated by transition_manifest()
        "json_fields": set(),
        "bool_fields": set(),
    },
    "cost_models": {
        "id_field": "cost_model_id",
        "json_fields": {"commission_rules", "tax_assumptions"},
        "bool_fields": set(),
    },
}

_META_COLUMNS = ("sequence_number", "record_hash", "previous_record_hash")


def _serialize_row(table: str, payload: dict) -> dict:
    """payload (native dicts/bools) -> flat dict of storage-ready values
    (JSON fields dumped to text, bools cast to int)."""
    meta = _LEDGER_TABLES[table]
    row = {}
    for k, v in payload.items():
        if k in meta["json_fields"]:
            row[k] = canonical_json(v) if v is not None else None
        elif k in meta["bool_fields"]:
            row[k] = int(bool(v))
        else:
            row[k] = v
    return row


def _deserialize_row(table: str, row: dict) -> dict:
    """Inverse of _serialize_row -- reconstructs the native payload dict
    from a stored row, for hash verification. Every column is hashed and
    immutable (all Group A tables, decision_events included as of v1.2) --
    there is no per-table exclusion list to apply here."""
    meta = _LEDGER_TABLES[table]
    payload = {}
    for k, v in row.items():
        if k in _META_COLUMNS:
            continue
        if k in meta["json_fields"]:
            payload[k] = json.loads(v) if v is not None else None
        elif k in meta["bool_fields"]:
            payload[k] = bool(v)
        else:
            payload[k] = v
    return payload


def _latest_hash(conn: sqlite3.Connection, table: str) -> str:
    row = conn.execute(
        f"SELECT record_hash FROM {table} ORDER BY sequence_number DESC LIMIT 1"
    ).fetchone()
    return row[0] if row else GENESIS_HASH


def append_ledger_row(conn: sqlite3.Connection, table: str, payload: dict) -> dict:
    """Insert a row into a Group A ledger table, computing its hash chain
    link. Group A tables only -- raises for anything else."""
    if table not in _LEDGER_TABLES:
        raise ValueError(f"append_ledger_row: {table!r} is not a Group A ledger table")

    previous_hash = _latest_hash(conn, table)
    record_hash = compute_record_hash(payload, previous_hash)

    storage_row = _serialize_row(table, payload)
    storage_row["record_hash"] = record_hash
    storage_row["previous_record_hash"] = previous_hash

    cols = list(storage_row.keys())
    placeholders = ",".join("?" for _ in cols)
    conn.execute(
        f"INSERT INTO {table} ({','.join(cols)}) VALUES ({placeholders})",
        [storage_row[c] for c in cols],
    )
    conn.commit()

    full_row = dict(payload)
    full_row["record_hash"] = record_hash
    full_row["previous_record_hash"] = previous_hash
    full_row["sequence_number"] = conn.execute(
        f"SELECT sequence_number FROM {table} WHERE record_hash=?", (record_hash,)
    ).fetchone()[0]
    return full_row


def verify_chain(conn: sqlite3.Connection, table: str) -> list[dict]:
    """Walk table's hash chain end-to-end. Returns a list of break
    descriptions (empty = clean chain). Checks both that each row's
    record_hash matches its own payload+previous_hash, AND that its stored
    previous_record_hash matches the prior row's actual record_hash --
    tampering with either the payload or the chain linkage is caught."""
    if table not in _LEDGER_TABLES:
        raise ValueError(f"verify_chain: {table!r} is not a Group A ledger table")

    cur = conn.execute(f"SELECT * FROM {table} ORDER BY sequence_number ASC")
    cols = [d[0] for d in cur.description]
    breaks: list[dict] = []
    expected_previous = GENESIS_HASH

    for raw in cur.fetchall():
        row = dict(zip(cols, raw))
        payload = _deserialize_row(table, row)
        recomputed = compute_record_hash(payload, row["previous_record_hash"])

        if row["previous_record_hash"] != expected_previous:
            breaks.append({
                "sequence_number": row["sequence_number"],
                "reason": "previous_record_hash does not match prior row's record_hash",
                "expected_previous": expected_previous,
                "stored_previous": row["previous_record_hash"],
            })
        if recomputed != row["record_hash"]:
            breaks.append({
                "sequence_number": row["sequence_number"],
                "reason": "record_hash does not match recomputed hash of stored payload",
                "expected": recomputed,
                "stored": row["record_hash"],
            })
        expected_previous = row["record_hash"]

    return breaks


def verify_all_chains(conn: sqlite3.Connection) -> dict[str, list[dict]]:
    """verify_chain() for every Group A table. Result maps table -> breaks
    (empty list = clean)."""
    return {table: verify_chain(conn, table) for table in _LEDGER_TABLES}


# ── Deployment manifest lifecycle (FR-0.9) ───────────────────────────────────

MANIFEST_TRANSITIONS: dict[str | None, set[str]] = {
    None: {"CREATED"},
    "CREATED": {"TESTING_STARTED"},
    "TESTING_STARTED": {"REVIEW_REQUESTED"},
    "REVIEW_REQUESTED": {"APPROVED"},
    "APPROVED": {"PROMOTED"},
    "PROMOTED": {"RETIRED"},
    "RETIRED": set(),
}


def get_manifest_state(conn: sqlite3.Connection, manifest_id: str) -> str | None:
    """Latest lifecycle event_type for manifest_id, or None if it has never
    had one (the pre-CREATED virtual start state)."""
    row = conn.execute(
        "SELECT event_type FROM deployment_manifest_events "
        "WHERE manifest_id=? ORDER BY sequence_number DESC LIMIT 1",
        (manifest_id,),
    ).fetchone()
    return row[0] if row else None


def _get_approval_event_id_for_manifest(conn: sqlite3.Connection, manifest_id: str) -> str | None:
    row = conn.execute(
        "SELECT approval_event_id FROM deployment_manifest_events "
        "WHERE manifest_id=? AND event_type='APPROVED' ORDER BY sequence_number DESC LIMIT 1",
        (manifest_id,),
    ).fetchone()
    return row[0] if row else None


def _generate_manifest_event_id(conn: sqlite3.Connection, timestamp: str) -> str:
    """MFE-YYYYMMDD-NNN (v1.3) -- deployment_manifest_events' own semantic
    identifier, generated here since transition_manifest() is the only
    entry point that ever creates these rows (unlike decision_id etc.,
    which are supplied by whatever Phase 1A wiring eventually calls
    append_ledger_row directly)."""
    date_part = timestamp[:10].replace("-", "")
    count = conn.execute(
        "SELECT COUNT(*) FROM deployment_manifest_events WHERE event_id LIKE ?",
        (f"MFE-{date_part}-%",),
    ).fetchone()[0]
    return f"MFE-{date_part}-{count + 1:03d}"


def transition_manifest(
    conn: sqlite3.Connection, manifest_id: str, event_type: str, timestamp: str,
    approval_event_id: str | None = None,
) -> dict:
    """The only way to move a manifest through its lifecycle. Validates
    against MANIFEST_TRANSITIONS and requires a linked approval_event_id for
    APPROVED (FR-0.9). Updates active_deployment_pointer on PROMOTED, clears
    it (by row deletion, v1.3) on RETIRED.

    For PROMOTED, approval_event_id is auto-resolved from the manifest's own
    prior APPROVED event if the caller doesn't pass one explicitly (v1.2,
    FR-0.12) -- the schema's CHECK constraint requires every PROMOTED row to
    carry a non-null approval_event_id regardless of what inserted it, so
    callers shouldn't need to re-supply an approval they already gave once."""
    current = get_manifest_state(conn, manifest_id)
    legal = MANIFEST_TRANSITIONS.get(current, set())
    if event_type not in legal:
        raise ValueError(
            f"Illegal manifest transition for {manifest_id}: {current} -> {event_type} "
            f"(legal from {current}: {sorted(legal) or 'none'})"
        )
    if event_type == "APPROVED" and not approval_event_id:
        raise ValueError("APPROVED transition requires a linked approval_event_id (FR-0.9)")
    if event_type == "PROMOTED" and not approval_event_id:
        approval_event_id = _get_approval_event_id_for_manifest(conn, manifest_id)
        if not approval_event_id:
            raise ValueError(
                f"PROMOTED transition requires a linked approval_event_id (FR-0.12), "
                f"and none could be auto-resolved from a prior APPROVED event for {manifest_id}"
            )

    row = append_ledger_row(conn, "deployment_manifest_events", {
        "event_id": _generate_manifest_event_id(conn, timestamp),
        "manifest_id": manifest_id,
        "event_type": event_type,
        "approval_event_id": approval_event_id,
        "timestamp": timestamp,
    })

    if event_type == "PROMOTED":
        _set_active_pointer(conn, manifest_id, timestamp)
    elif event_type == "RETIRED":
        _clear_active_pointer_if_matches(conn, manifest_id)

    return row


def _set_active_pointer(conn: sqlite3.Connection, manifest_id: str, timestamp: str) -> None:
    """v1.3: active_manifest_id is NOT NULL -- replace the single row
    outright (INSERT OR REPLACE on the id=1 PK) rather than an ON CONFLICT
    UPDATE, since there's no NULL case to preserve/merge around."""
    conn.execute(
        "INSERT OR REPLACE INTO active_deployment_pointer (id, active_manifest_id, updated_at) "
        "VALUES (1, ?, ?)",
        (manifest_id, timestamp),
    )
    conn.commit()


def _clear_active_pointer_if_matches(conn: sqlite3.Connection, manifest_id: str) -> None:
    """v1.3: "no active deployment" is row absence, not active_manifest_id
    set to NULL (which would violate the column's NOT NULL constraint
    anyway). Clearing means DELETE, never UPDATE."""
    conn.execute(
        "DELETE FROM active_deployment_pointer WHERE id=1 AND active_manifest_id=?",
        (manifest_id,),
    )
    conn.commit()


def rebuild_active_pointer(conn: sqlite3.Connection) -> str | None:
    """Recompute "what's active right now" purely from
    deployment_manifest_events, ignoring the active_deployment_pointer
    cache entirely -- used by the integrity job to detect cache drift."""
    manifest_ids = [
        r[0] for r in conn.execute(
            "SELECT DISTINCT manifest_id FROM deployment_manifest_events"
        ).fetchall()
    ]
    promoted_not_retired = [
        (mid, get_manifest_state(conn, mid)) for mid in manifest_ids
    ]
    active = [mid for mid, state in promoted_not_retired if state == "PROMOTED"]
    if not active:
        return None
    if len(active) > 1:
        # Should not happen in a correctly-operated system (a new manifest
        # promoted without retiring the previous one first) -- defensively
        # pick the most recently promoted rather than raise, since this is
        # a read-only reconciliation check, not a place to halt the app.
        rows = conn.execute(
            "SELECT manifest_id, MAX(sequence_number) FROM deployment_manifest_events "
            "WHERE event_type='PROMOTED' AND manifest_id IN ({}) GROUP BY manifest_id".format(
                ",".join("?" for _ in active)
            ),
            active,
        ).fetchall()
        active_sorted = sorted(rows, key=lambda r: r[1], reverse=True)
        return active_sorted[0][0]
    return active[0]


# ── Decision lifecycle state (FR-0.11, v1.2: derived, not stored) ───────────

def get_decision_state(conn: sqlite3.Connection, decision_id: str) -> str | None:
    """OPEN or CLOSED, read from the decision_state view (schema.sql Section
    5.1a) -- purely derived from whether a decision_outcome_events row
    exists for this decision_id. None if no such decision exists at all.

    There is no "mark closed" call: appending a decision_outcome_events row
    via append_ledger_row() IS the entire OPEN -> CLOSED transition, and
    ANALYZED is deliberately not modeled in Phase 0 (Phase 1 calibration-
    batch design, not yet built)."""
    row = conn.execute(
        "SELECT outcome_state FROM decision_state WHERE decision_id=?", (decision_id,)
    ).fetchone()
    return row[0] if row else None
