"""ID generators for Trust Ledger rows written by the live trading engine.

Most ids are <PREFIX>-<UTC compact timestamp>-<symbol or NA>-<8 hex chars>.
The random suffix makes these collision-safe without a counter query against
the ledger DB (unlike deployment_manifest_events.event_id, which ledger.py
generates internally via a same-day COUNT() since transition_manifest() is
the only writer for that table -- these ids are generated by many call
sites across the live trading loop, so a counter query would mean an extra
DB round-trip per decision).

Exception: new_cost_model_id() deliberately does NOT follow this pattern --
cost models are low-cardinality and human-versioned (schema's own example is
"cost_model_v1.2"), so it returns a bare "cost_model_<label>" with no
collision protection. Calling it twice with the same label is a caller
error, not something this function guards against.
"""
from __future__ import annotations

import uuid
from datetime import datetime, timezone


def _new_id(prefix: str, symbol: str | None = None) -> str:
    ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S")
    sym = symbol or "NA"
    return f"{prefix}-{ts}-{sym}-{uuid.uuid4().hex[:8]}"


def new_candidate_event_id(symbol: str) -> str:
    return _new_id("CAND", symbol)


def new_decision_id(symbol: str) -> str:
    return _new_id("DEC", symbol)


def new_event_id(symbol: str | None = None) -> str:
    """For risk_evaluation_events -- portfolio-level, no symbol."""
    return _new_id("RISK", symbol)


def new_outcome_id(symbol: str) -> str:
    return _new_id("OUT", symbol)


def new_approval_id() -> str:
    return _new_id("APR")


def new_cost_model_id(label: str) -> str:
    return f"cost_model_{label}"


def new_constitution_event_id() -> str:
    """For constitution_enforcement_events -- one per rule check, several per decision."""
    return _new_id("CONST")


def new_data_quality_event_id() -> str:
    """For data_quality_events -- portfolio-level, no symbol."""
    return _new_id("DQ")


def new_confidence_event_id(symbol: str | None = None) -> str:
    """For decision_confidence_events -- Confidence Integrity Redesign Phase 1."""
    return _new_id("CONF", symbol)
