"""Phase 1A Sprint 5 -- the Executor interface both AlpacaClient and
PaperExecutor satisfy structurally (no inheritance needed -- Python's
duck typing plus this Protocol is enough for bot/main.py's call sites to
treat either interchangeably).

Enumerated from every bot/*.py call site that calls a method on `client`
(grepped, not guessed) -- this is the FULL surface the live pipeline uses,
not just buy/sell: market-data reads (get_bars, get_latest_price) are part
of it too, since paper trading still needs real prices to simulate
realistic fills against.
"""
from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class Executor(Protocol):
    api: Any  # TradingClient for AlpacaClient, None for PaperExecutor (see paper_executor.py)

    def get_account(self) -> Any: ...
    def get_account_summary(self) -> tuple[float, float]: ...
    def get_portfolio_value(self) -> float: ...
    def get_cash(self) -> float: ...
    def get_positions(self) -> dict: ...
    def get_latest_price(self, symbol: str) -> float: ...
    def get_bars(self, symbol: str, timeframe: str = "5Min", limit: int = 100) -> Any: ...
    def buy(self, symbol: str, notional: float, limit_price: float | None = None) -> dict | None: ...
    def sell(self, symbol: str, qty: float | None = None, limit_price: float | None = None) -> dict | None: ...
    def sell_market(self, symbol: str, qty: float) -> dict | None: ...
    def wait_for_fill(self, order_id: str, timeout_secs: int = 15) -> float: ...
    def get_fill_price(self, order_id: str) -> float | None: ...
    def get_open_order_symbols(self) -> tuple[set[str], set[str]]: ...
    def get_position_value(self, symbol: str, positions: dict | None = None) -> float: ...
    def get_position_pnl_pct(self, symbol: str, positions: dict | None = None) -> float: ...
